import type { CalibratedBands } from "./conformal.js";

/**
 * Committed band calibration artifact — GENERATED DATA, do NOT hand-edit.
 *
 * Regenerated by the offline dev script (`pnpm tsx src/regenerate-bands.ts`),
 * which runs the issue-time backtest over real exported price/Fingrid history,
 * derives per-UTC-hour residual offsets, measures out-of-sample coverage, and
 * rewrites this module. A human reviews and commits the result. This is the ONLY
 * band-related thing shipped on the request path: a static lookup table.
 *
 * Shipped state: `calibrated: false` (bands DARK). Real exported history is
 * still too thin to clear the coverage ship gate (≥ 0.70 observed vs 0.80
 * nominal), so no offsets are emitted and the forecast endpoint returns its
 * point estimate with `bands.calibrated: false` and no bound fields. Bands turn
 * on with no code change once a regenerated `calibrated: true` artifact that
 * clears the gate is reviewed and committed here.
 */
export const CALIBRATED_BANDS: CalibratedBands = {
  method: "empirical-residual",
  nominalCoverage: 0.8,
  observedCoverage: null,
  calibrated: false,
  offsetsByHour: new Map(),
  globalOffsets: null,
  generatedAt: "",
};
