import type { CalibratedBands } from "./conformal.js";

/**
 * Committed band calibration artifact — GENERATED DATA, do NOT hand-edit.
 *
 * Regenerated by the offline dev script (`pnpm tsx src/regenerate-bands.ts`),
 * which runs the issue-time backtest over real exported price/Fingrid history,
 * derives per-UTC-hour residual offsets, measures out-of-sample coverage, and
 * rewrites this module. A human reviews and commits the result. This is the ONLY
 * band-related thing shipped on the request path: a static lookup table.
 *
 * `calibrated: false`. Bands are emitted by the forecast
 * endpoint only when calibrated is true (observed coverage cleared the gate);
 * otherwise the endpoint returns its point estimate with `bands.calibrated:
 * false` and no bound fields. Bands turn on/off purely by committing a new
 * artifact here — no code change.
 *
 * Provenance (issue #80):
 *   scored window: 2026-06-24T13:00:00.000Z … 2026-07-15T13:00:00.000Z
 *   scored origins: 22   span: 21.0 days
 *   SUMMER-ONLY — NOT validated across seasons; shipped DARK by the 90-day window guard.
 *   measured out-of-sample coverage: 0.801 (shipped field is null while dark — see conformal.ts contract)
 */
export const CALIBRATED_BANDS: CalibratedBands = {
  method: "empirical-residual",
  nominalCoverage: 0.8,
  observedCoverage: null,
  calibrated: false,
  offsetsByHour: new Map(),
  globalOffsets: null,
  generatedAt: "",
};
