/**
 * OFFLINE / DEV-ONLY regeneration script for the conformal band artifact.
 *
 * IMPORTANT: this module must NOT be imported by any route, `index.ts`, or
 * `app.ts`, and is NOT part of `$BUILD_CMD` or the request path. Like
 * `backtest.ts`, the production bundle's only tsup entry is `src/index.ts` and
 * nothing in that graph imports this file, so it never reaches `dist/`. It runs
 * only as a tsx script:
 *
 *     pnpm tsx src/regenerate-bands.ts --data tools/backtest-data
 *
 * It runs the issue-time, leakage-guarded backtest over real exported
 * price/Fingrid history, derives per-UTC-hour residual offsets and measured
 * out-of-sample coverage (`conformal.ts`), and rewrites `conformal-artifact.ts`.
 * A human reviews and commits the result. Regenerating the artifact is a
 * documented PERIODIC MANUAL CHORE — NOT a background job (`STACK §9`). Bands
 * turn on (or off) purely by committing a new artifact; no code change.
 *
 * This script reads `node:fs`, `process.argv`, and writes the artifact file. It
 * never reads `process.env`, the network, or the DB.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { deriveBandsFromBacktest, loadFixture } from "./backtest.js";
import type { BandOffsets, CalibratedBands } from "./conformal.js";

const offsetsLiteral = (o: BandOffsets): string =>
  `{ lowOffset: ${String(o.lowOffset)}, highOffset: ${String(o.highOffset)} }`;

const mapLiteral = (m: ReadonlyMap<number, BandOffsets>): string => {
  if (m.size === 0) {
    return "new Map()";
  }
  const entries = [...m.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([hour, off]) => `    [${String(hour)}, ${offsetsLiteral(off)}],`)
    .join("\n");
  return `new Map([\n${entries}\n  ])`;
};

/** Render the `CalibratedBands` artifact as a committable TypeScript module. */
export const renderArtifact = (bands: CalibratedBands): string => {
  const observed =
    bands.observedCoverage === null ? "null" : String(bands.observedCoverage);
  const global =
    bands.globalOffsets === null ? "null" : offsetsLiteral(bands.globalOffsets);
  return `import type { CalibratedBands } from "./conformal.js";

/**
 * Committed band calibration artifact — GENERATED DATA, do NOT hand-edit.
 *
 * Regenerated by the offline dev script (\`pnpm tsx src/regenerate-bands.ts\`),
 * which runs the issue-time backtest over real exported price/Fingrid history,
 * derives per-UTC-hour residual offsets, measures out-of-sample coverage, and
 * rewrites this module. A human reviews and commits the result. This is the ONLY
 * band-related thing shipped on the request path: a static lookup table.
 *
 * \`calibrated: ${String(bands.calibrated)}\`. Bands are emitted by the forecast
 * endpoint only when calibrated is true (observed coverage cleared the gate);
 * otherwise the endpoint returns its point estimate with \`bands.calibrated:
 * false\` and no bound fields. Bands turn on/off purely by committing a new
 * artifact here — no code change.
 */
export const CALIBRATED_BANDS: CalibratedBands = {
  method: "empirical-residual",
  nominalCoverage: ${String(bands.nominalCoverage)},
  observedCoverage: ${observed},
  calibrated: ${String(bands.calibrated)},
  offsetsByHour: ${mapLiteral(bands.offsetsByHour)},
  globalOffsets: ${global},
  generatedAt: ${JSON.stringify(bands.generatedAt)},
};
`;
};

const main = (): void => {
  const dirArgIdx = process.argv.indexOf("--data");
  const here = path.dirname(fileURLToPath(import.meta.url));
  const dataDir =
    dirArgIdx >= 0 && process.argv[dirArgIdx + 1] !== undefined
      ? (process.argv[dirArgIdx + 1] as string)
      : path.join(here, "..", "tools", "backtest-data");

  const data = loadFixture(dataDir);
  const { summary, bands } = deriveBandsFromBacktest(
    data,
    new Date().toISOString(),
  );

  const outPath = path.join(here, "conformal-artifact.ts");
  writeFileSync(outPath, renderArtifact(bands), "utf-8");

  console.log(`\nConformal band artifact regenerated → ${outPath}`);
  console.log(`  residuals:           ${String(summary.residuals.length)}`);
  console.log(`  leakage-free:        ${String(summary.leakFree)}`);
  console.log(
    `  calibrated:          ${String(bands.calibrated)} (observed coverage ${
      bands.observedCoverage === null
        ? "n/a"
        : bands.observedCoverage.toFixed(3)
    } vs nominal ${String(bands.nominalCoverage)})`,
  );
  if (!bands.calibrated) {
    console.log(
      "  → shipping DARK: coverage below the gate or too few samples. Review before committing.",
    );
  }
  console.log("");
};

// Run only when invoked as a script, never on import.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
